#!/usr/bin/env bash
echo -e '\e[31;2m[+] Usuario atual:\e[m'         $(echo $USER)
echo -e '\e[31;2m[+] Shell atual:\e[m'           $(echo $SHELL)
echo -e '\e[31;2m[+] Shells do sistema:\e[m'     $(cat /etc/shells)
echo -e '\e[31;2m[+] Caminho atual:\e[m'         $(pwd)
echo -e '\e[31;2m[+] Tempo de atividade:\e[m'    $(uptime -p)
echo -e '\e[31;2m[+] Kernel:\e[m'                $(uname -r)
echo -e '\e[31;2m[+] Arquitetura:\e[m'           $(uname -m); echo ""
echo -e '\e[31;2m[+] Processador:\e[m';          cat /proc/cpuinfo | grep "model name" | sort -u; echo ""
echo -e '\e[31;2m[+] Versao do sistema:\e[m';    cat /etc/*-release
echo -e '\e[31;2m[+] Memoria:\e[m';              free -h; echo ""
echo -e '\e[31;2m[+] Tabela de rotas:\e[m';      route; echo ""
echo -e '\e[31;2m[+] Adaptadores de rede:\e[m';  ip a | egrep -v "link|valid|inet6"; echo ""
echo -e '\e[31;2m[+] Portas TCP local:\e[m';     netstat -lpt; echo ""
echo -e '\e[31;2m[+] Portas UDP local:\e[m';     netstat -lpu; echo ""
echo -e '\e[31;2m[+] Servicos em ativos:\e[m';        service --status-all | grep "[+]"; echo ""
echo -e '\e[31;2m[+] Registro de LOGS da raiz:\e[m';  ls /var/log | grep "log"; echo ""
echo -e '\e[31;2m[+] Espaco em DISCO:\e[m';           df -h;echo ""
echo -e '\e[31;2m[+] Informacoes de SSH:\e[m'
echo "Caminho: /etc/root/";                       ls /root/.ssh; echo ""
echo "Caminho: /etc/ssh/";                        ls /etc/ssh; echo ""
echo -e '\e[31;2m[+] Processos em execucao:\e[m'; ps -eo pid,comm; echo ""
echo -e '\e[31;2m[+] Processos excutando como root :\e[m'; ps -aux | grep root; echo ""
echo -e '\e[31;2m[+] Constas de usuarios:\e[m';   cat /etc/passwd; echo ""
echo -e '\e[31;2m[+] Senhas de usuarios:\e[m';    cat /etc/shadow; echo ""
echo -e '\e[31;2m[+] Tarefas agendadas:\e[m';     cat /etc/crontab; echo ""
echo -e '\e[31;2m[+] Tarefas agendadas:\e[m';     crontab -u root -l; echo ""
echo -e '\e[31;2m[+] Diretório cron.daily:\e[m';    ls -la /etc/cron.daily; echo ""
echo -e '\e[31;2m[+] Diretório cron.hourly:\e[m';   ls -la /etc/cron.hourly; echo ""
echo -e '\e[31;2m[+] Diretório cron.monthly:\e[m';  ls -la /etc/cron.monthly; echo ""
echo -e '\e[31;2m[+] Diretório cron.weekly:\e[m';   ls -la /etc/cron.weekly; echo ""
echo -e '\e[31;2m[+] Arquivos com permissão SUID...\e[m'; find / -perm -u=s -type f 2>/dev/null
echo -e '\e[31;2m[+] Arquivos com permisão 777...\e[m';   find / -type f -perm 777 2>/dev/null
echo -e '\e[31;2m[+] Diretórios com permissão de escrita...\e[m'; find / -witable -type d 2>/dev/null
echo -e '\e[31;2m[+] programas executando como root...\e[m'; sudo -l
echo -e '\e[31;2m[+] Programas configurados para executar como root...\e[m'; cat /etc/sudoers
echo -e '\e[31;2m[+] Programas instalados:\e[m'; dpkg --get-selections | awk '{if ($2=="install") print $1}' 
